---
# tasks file for ansible-role-postgres

- name: "Ensure PostgreSQL database has been created"
  community.postgresql.postgresql_db:
    login_password: "{{ postgres_password}}"
    login_host: localhost
    port: "{{ postgres_port }}" # login_port
    name: "{{ outer_item.database }}"
    owner: "{{ outer_item.owner | default(omit) }}"
    conn_limit: "{{outer_item.con_limit | default(100) }}"
    state: "{{ outer_item.state | default('present') }}"
  when: outer_item.database is defined
