---
# tasks file for ansible-role-postgres

- name: "Ensure PostgreSQL role has been created"
  community.postgresql.postgresql_user:
    login_password: "{{ postgres_password}}"
    login_host: localhost
    port: "{{ postgres_port }}" # login_port
    name: "{{ outer_item.role }}"
    password: "{{ outer_item.password }}"
    role_attr_flags: "{{ outer_item.role_attr_flags | default('LOGIN,NOSUPERUSER') }}"
    priv: "{{ outer_item.priv | default(omit) }}"
    expires: "{{ outer_item.expires | default('infinity') }}"
    state: "{{ outer_item.state | default('present') }}"
    comment: "{{ outer_item.comment | default(omit) }}"
  environment:
    PGOPTIONS: "-c password_encryption=scram-sha-256"
  when: outer_item.role is defined and outer_item.password is defined
