---
# handlers file for ansible-role-postgres

- name: Restart PostgreSQL
  command: "docker restart {{ postgres_container_name }}"
  listen: restart postgres

- name: Wait until PostgreSQL starts up
  wait_for:
    port: "{{ postgres_port }}"
    delay: 5
  listen: restart postgres
