---
# handlers file for ansible-role-postgres

- name: Restart PostgreSQL
  ansible.builtin.command: "docker restart {{ postgres_container_name }}"
  listen: restart postgres

- name: Wait until PostgreSQL starts up
  ansible.builtin.wait_for:
    port: "{{ postgres_port }}"
    delay: 5
  listen: restart postgres
